Map<String, Map<String, dynamic>> currencies = {

  "USD": {
    "code": "USD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "USD",
    "name": "United States Dollar",
    "name_plural": "US dollars",
    "number": 840,
    "space_between_amount_and_symbol": false,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "EUR": {
    "code": "EUR",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "EUR",
    "name": "Euro",
    "name_plural": "euros",
    "number": 978,
    "space_between_amount_and_symbol": true,
    "symbol": "\u20ac",
    "symbol_on_left": false,
    "thousands_separator": "."
  },
  "JPY": {
    "code": "JPY",
    "decimal_digits": 0,
    "decimal_separator": ".",
    "flag": "JPY",
    "name": "Japanese Yen",
    "name_plural": "Japanese yen",
    "number": 392,
    "space_between_amount_and_symbol": false,
    "symbol": "\u00a5",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "GBP": {
    "code": "GBP",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "GBP",
    "name": "British Pound",
    "name_plural": "British pounds sterling",
    "number": 826,
    "space_between_amount_and_symbol": false,
    "symbol": "\u00a3",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "AUD": {
    "code": "AUD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "AUD",
    "name": "Australian Dollar",
    "name_plural": "Australian dollars",
    "number": 36,
    "space_between_amount_and_symbol": false,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "CAD": {
    "code": "CAD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "CAD",
    "name": "Canadian Dollar",
    "name_plural": "Canadian dollars",
    "number": 124,
    "space_between_amount_and_symbol": false,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "CHF": {
    "code": "CHF",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "CHF",
    "name": "Switzerland Franc",
    "name_plural": "Swiss francs",
    "number": 756,
    "space_between_amount_and_symbol": true,
    "symbol": "CHF",
    "symbol_on_left": true,
    "thousands_separator": "'"
  },
  "CNY": {
    "code": "CNY",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "CNY",
    "name": "China Yuan Renminbi",
    "name_plural": "Chinese yuan",
    "number": 156,
    "space_between_amount_and_symbol": false,
    "symbol": "\u00a5",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "HKD": {
    "code": "HKD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "HKD",
    "name": "Hong Kong Dollar",
    "name_plural": "Hong Kong dollars",
    "number": 344,
    "space_between_amount_and_symbol": false,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "NZD": {
    "code": "NZD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "NZD",
    "name": "New Zealand Dollar",
    "name_plural": "New Zealand dollars",
    "number": 554,
    "space_between_amount_and_symbol": false,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "SEK": {
    "code": "SEK",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "SEK",
    "name": "Sweden Krona",
    "name_plural": "Swedish kronor",
    "number": 752,
    "space_between_amount_and_symbol": true,
    "symbol": "kr",
    "symbol_on_left": false,
    "thousands_separator": "."
  },
  "KRW": {
    "code": "KRW",
    "decimal_digits": 0,
    "decimal_separator": ".",
    "flag": "KRW",
    "name": "Korea (South) Won",
    "name_plural": "South Korean won",
    "number": 410,
    "space_between_amount_and_symbol": false,
    "symbol": "\u20a9",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "SGD": {
    "code": "SGD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "SGD",
    "name": "Singapore Dollar",
    "name_plural": "Singapore dollars",
    "number": 702,
    "space_between_amount_and_symbol": false,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "NOK": {
    "code": "NOK",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "NOK",
    "name": "Norway Krone",
    "name_plural": "Norwegian kroner",
    "number": 578,
    "space_between_amount_and_symbol": true,
    "symbol": "kr",
    "symbol_on_left": true,
    "thousands_separator": "."
  },
  "MXN": {
    "code": "MXN",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "MXN",
    "name": "Mexico Peso",
    "name_plural": "Mexican pesos",
    "number": 484,
    "space_between_amount_and_symbol": false,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "INR": {
    "code": "INR",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "INR",
    "name": "Indian Rupee",
    "name_plural": "Indian rupees",
    "number": 356,
    "space_between_amount_and_symbol": false,
    "symbol": "\u20b9",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "RUB": {
    "code": "RUB",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "RUB",
    "name": "Russia Ruble",
    "name_plural": "Russian rubles",
    "number": 643,
    "space_between_amount_and_symbol": true,
    "symbol": "\u20bd",
    "symbol_on_left": false,
    "thousands_separator": "."
  },
  "ZAR": {
    "code": "ZAR",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "ZAR",
    "name": "South Africa Rand",
    "name_plural": "South African rand",
    "number": 710,
    "space_between_amount_and_symbol": false,
    "symbol": "R",
    "symbol_on_left": true,
    "thousands_separator": "."
  },
  "TRY": {
    "code": "TRY",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "TRY",
    "name": "Turkish Lira",
    "name_plural": "Turkish Lira",
    "number": 949,
    "space_between_amount_and_symbol": false,
    "symbol": "\u20ba",
    "symbol_on_left": true,
    "thousands_separator": "."
  },
  "BRL": {
    "code": "BRL",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "BRL",
    "name": "Brazil Real",
    "name_plural": "Brazilian reals",
    "number": 986,
    "space_between_amount_and_symbol": true,
    "symbol": "R\$",
    "symbol_on_left": true,
    "thousands_separator": "."
  },
  "TWD": {
    "code": "TWD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "TWD",
    "name": "Taiwan New Dollar",
    "name_plural": "New Taiwan dollars",
    "number": 901,
    "space_between_amount_and_symbol": false,
    "symbol": "NT\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "DKK": {
    "code": "DKK",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "DKK",
    "name": "Denmark Krone",
    "name_plural": "Danish kroner",
    "number": 208,
    "space_between_amount_and_symbol": true,
    "symbol": "kr",
    "symbol_on_left": false,
    "thousands_separator": ""
  },
  "PLN": {
    "code": "PLN",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "PLN",
    "name": "Poland Zloty",
    "name_plural": "Polish zlotys",
    "number": 985,
    "space_between_amount_and_symbol": true,
    "symbol": "z\u0142",
    "symbol_on_left": false,
    "thousands_separator": "."
  },
  "THB": {
    "code": "THB",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "THB",
    "name": "Thailand Baht",
    "name_plural": "Thai baht",
    "number": 764,
    "space_between_amount_and_symbol": false,
    "symbol": "\u0e3f",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "IDR": {
    "code": "IDR",
    "decimal_digits": 0,
    "decimal_separator": ",",
    "flag": "IDR",
    "name": "Indonesia Rupiah",
    "name_plural": "Indonesian rupiahs",
    "number": 360,
    "space_between_amount_and_symbol": false,
    "symbol": "Rp",
    "symbol_on_left": true,
    "thousands_separator": "."
  },
  "HUF": {
    "code": "HUF",
    "decimal_digits": 0,
    "decimal_separator": ",",
    "flag": "HUF",
    "name": "Hungary Forint",
    "name_plural": "Hungarian forints",
    "number": 348,
    "space_between_amount_and_symbol": true,
    "symbol": "Ft",
    "symbol_on_left": false,
    "thousands_separator": "."
  },
  "CZK": {
    "code": "CZK",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "CZK",
    "name": "Czech Koruna",
    "name_plural": "Czech Republic korunas",
    "number": 203,
    "space_between_amount_and_symbol": true,
    "symbol": "K\u010d",
    "symbol_on_left": false,
    "thousands_separator": "."
  },
  "ILS": {
    "code": "ILS",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "ILS",
    "name": "Israel Shekel",
    "name_plural": "Israeli new sheqels",
    "number": 376,
    "space_between_amount_and_symbol": true,
    "symbol": "\u20aa",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "CLP": {
    "code": "CLP",
    "decimal_digits": 0,
    "decimal_separator": ",",
    "flag": "CLP",
    "name": "Chile Peso",
    "name_plural": "Chilean pesos",
    "number": 152,
    "space_between_amount_and_symbol": true,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": "."
  },
  "PHP": {
    "code": "PHP",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "PHP",
    "name": "Philippines Peso",
    "name_plural": "Philippine pesos",
    "number": 608,
    "space_between_amount_and_symbol": false,
    "symbol": "\u20b1",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "AED": {
    "code": "AED",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "AED",
    "name": "Emirati Dirham",
    "name_plural": "UAE dirhams",
    "number": 784,
    "space_between_amount_and_symbol": true,
    "symbol": "\u062f.\u0625",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "COP": {
    "code": "COP",
    "decimal_digits": 0,
    "decimal_separator": ",",
    "flag": "COP",
    "name": "Colombia Peso",
    "name_plural": "Colombian pesos",
    "number": 170,
    "space_between_amount_and_symbol": true,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": "."
  },
  "SAR": {
    "code": "SAR",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "SAR",
    "name": "Saudi Arabia Riyal",
    "name_plural": "Saudi riyals",
    "number": 682,
    "space_between_amount_and_symbol": true,
    "symbol": "\ufdfc",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "MYR": {
    "code": "MYR",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "MYR",
    "name": "Malaysia Ringgit",
    "name_plural": "Malaysian ringgits",
    "number": 458,
    "space_between_amount_and_symbol": false,
    "symbol": "RM",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "RON": {
    "code": "RON",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "RON",
    "name": "Romania Leu",
    "name_plural": "Romanian lei",
    "number": 946,
    "space_between_amount_and_symbol": true,
    "symbol": "L",
    "symbol_on_left": false,
    "thousands_separator": "."
  },
  "AFN": {
    "code": "AFN",
    "decimal_digits": 0,
    "decimal_separator": ".",
    "flag": "AFN",
    "name": "Afghanistan Afghani",
    "name_plural": "Afghan Afghanis",
    "number": 971,
    "space_between_amount_and_symbol": false,
    "symbol": "\u060b",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "ARS": {
    "code": "ARS",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "ARS",
    "name": "Argentine Peso",
    "name_plural": "Argentine pesos",
    "number": 32,
    "space_between_amount_and_symbol": true,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": "."
  },
  "BBD": {
    "code": "BBD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "BBD",
    "name": "Barbados Dollar",
    "name_plural": "Zimbabwean dollars",
    "number": 52,
    "space_between_amount_and_symbol": false,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "BDT": {
    "code": "BDT",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "BDT",
    "name": "Bangladeshi Taka",
    "name_plural": "Bangladeshi takas",
    "number": 50,
    "space_between_amount_and_symbol": true,
    "symbol": " Tk",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "BGN": {
    "code": "BGN",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "BGN",
    "name": "Bulgarian Lev",
    "name_plural": "Bulgarian leva",
    "number": 975,
    "space_between_amount_and_symbol": true,
    "symbol": "\u043b\u0432",
    "symbol_on_left": false,
    "thousands_separator": "."
  },
  "BHD": {
    "code": "BHD",
    "decimal_digits": 3,
    "decimal_separator": ".",
    "flag": "BHD",
    "name": "Bahraini Dinar",
    "name_plural": "Bahraini dinars",
    "number": 48,
    "space_between_amount_and_symbol": true,
    "symbol": "BD",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "BMD": {
    "code": "BMD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "BMD",
    "name": "Bermuda Dollar",
    "name_plural": "Bermuda dollars",
    "number": 60,
    "space_between_amount_and_symbol": false,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "BND": {
    "code": "BND",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "BND",
    "name": "Brunei Darussalam Dollar",
    "name_plural": "Brunei dollars",
    "number": 96,
    "space_between_amount_and_symbol": false,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": "."
  },
  "BOB": {
    "code": "BOB",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "BOB",
    "name": "Bolivia Bol\u00edviano",
    "name_plural": "Bolivian bolivianos",
    "number": 68,
    "space_between_amount_and_symbol": true,
    "symbol": "\$b",
    "symbol_on_left": true,
    "thousands_separator": "."
  },
  "BTN": {
    "code": "BTN",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "BTN",
    "name": "Bhutanese Ngultrum",
    "name_plural": "Bhutanese ngultrums",
    "number": 64,
    "space_between_amount_and_symbol": true,
    "symbol": "Nu.",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "BZD": {
    "code": "BZD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "BZD",
    "name": "Belize Dollar",
    "name_plural": "Belize dollars",
    "number": 84,
    "space_between_amount_and_symbol": false,
    "symbol": "BZ\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "CRC": {
    "code": "CRC",
    "decimal_digits": 0,
    "decimal_separator": ",",
    "flag": "CRC",
    "name": "Costa Rica Colon",
    "name_plural": "Costa Rican col\u00f3ns",
    "number": 188,
    "space_between_amount_and_symbol": false,
    "symbol": "\u20a1",
    "symbol_on_left": true,
    "thousands_separator": "."
  },
  "DOP": {
    "code": "DOP",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "DOP",
    "name": "Dominican Republic Peso",
    "name_plural": "Dominican pesos",
    "number": 214,
    "space_between_amount_and_symbol": false,
    "symbol": "RD\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "EGP": {
    "code": "EGP",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "EGP",
    "name": "Egypt Pound",
    "name_plural": "Egyptian pounds",
    "number": 818,
    "space_between_amount_and_symbol": true,
    "symbol": "\u00a3",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "ETB": {
    "code": "ETB",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "ETB",
    "name": "Ethiopian Birr",
    "name_plural": "Ethiopian birrs",
    "number": 230,
    "space_between_amount_and_symbol": false,
    "symbol": "Br",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "GEL": {
    "code": "GEL",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "GEL",
    "name": "Georgian Lari",
    "name_plural": "Georgian laris",
    "number": 981,
    "space_between_amount_and_symbol": true,
    "symbol": "\u20be",
    "symbol_on_left": false,
    "thousands_separator": "."
  },
  "GHS": {
    "code": "GHS",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "GHS",
    "name": "Ghana Cedi",
    "name_plural": "Ghanaian cedis",
    "number": 936,
    "space_between_amount_and_symbol": false,
    "symbol": "\u20b5",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "GMD": {
    "code": "GMD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "GMD",
    "name": "Gambian dalasi",
    "name_plural": "Gambian dalasis",
    "number": 270,
    "space_between_amount_and_symbol": false,
    "symbol": "D",
    "symbol_on_left": false,
    "thousands_separator": ","
  },
  "GYD": {
    "code": "GYD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "GYD",
    "name": "Guyana Dollar",
    "name_plural": "Guyana dollars",
    "number": 328,
    "space_between_amount_and_symbol": false,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "HRK": {
    "code": "HRK",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "HRK",
    "name": "Croatia Kuna",
    "name_plural": "Croatian kunas",
    "number": 191,
    "space_between_amount_and_symbol": true,
    "symbol": "kn",
    "symbol_on_left": false,
    "thousands_separator": "."
  },
  "ISK": {
    "code": "ISK",
    "decimal_digits": 0,
    "decimal_separator": ",",
    "flag": "ISK",
    "name": "Iceland Krona",
    "name_plural": "Icelandic kr\u00f3nur",
    "number": 352,
    "space_between_amount_and_symbol": true,
    "symbol": "kr",
    "symbol_on_left": false,
    "thousands_separator": "."
  },
  "JMD": {
    "code": "JMD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "JMD",
    "name": "Jamaica Dollar",
    "name_plural": "Jamaican dollars",
    "number": 388,
    "space_between_amount_and_symbol": false,
    "symbol": "J\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "KES": {
    "code": "KES",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "KES",
    "name": "Kenyan Shilling",
    "name_plural": "Kenyan shillings",
    "number": 404,
    "space_between_amount_and_symbol": false,
    "symbol": "KSh",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "KWD": {
    "code": "KWD",
    "decimal_digits": 3,
    "decimal_separator": ".",
    "flag": "KWD",
    "name": "Kuwaiti Dinar",
    "name_plural": "Kuwaiti dinars",
    "number": 414,
    "space_between_amount_and_symbol": true,
    "symbol": "\u062f.\u0643",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "KYD": {
    "code": "KYD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "KYD",
    "name": "Cayman Islands Dollar",
    "name_plural": "Cayman islands dollars",
    "number": 136,
    "space_between_amount_and_symbol": false,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "KZT": {
    "code": "KZT",
    "decimal_digits": 2,
    "decimal_separator": "-",
    "flag": "KZT",
    "name": "Kazakhstan Tenge",
    "name_plural": "Kazakhstani tenges",
    "number": 398,
    "space_between_amount_and_symbol": false,
    "symbol": "\u3012",
    "symbol_on_left": true,
    "thousands_separator": "."
  },
  "LAK": {
    "code": "LAK",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "LAK",
    "name": "Laos Kip",
    "name_plural": "Laos Kip",
    "number": 418,
    "space_between_amount_and_symbol": false,
    "symbol": "\u20ad",
    "symbol_on_left": false,
    "thousands_separator": ","
  },
  "LKR": {
    "code": "LKR",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "LKR",
    "name": "Sri Lanka Rupee",
    "name_plural": "Sri Lankan rupees",
    "number": 144,
    "space_between_amount_and_symbol": true,
    "symbol": "\u20a8",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "LRD": {
    "code": "LRD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "LRD",
    "name": "Liberia Dollar",
    "name_plural": "Liberia dollars",
    "number": 430,
    "space_between_amount_and_symbol": false,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "MAD": {
    "code": "MAD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "MAD",
    "name": "Moroccan Dirham",
    "name_plural": "Moroccan dirhams",
    "number": 504,
    "space_between_amount_and_symbol": true,
    "symbol": "MAD",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "MDL": {
    "code": "MDL",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "MDL",
    "name": "Moldovan Leu",
    "name_plural": "Moldovan lei",
    "number": 498,
    "space_between_amount_and_symbol": true,
    "symbol": "L",
    "symbol_on_left": false,
    "thousands_separator": ","
  },
  "MKD": {
    "code": "MKD",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "MKD",
    "name": "Macedonia Denar",
    "name_plural": "Macedonian denari",
    "number": 807,
    "space_between_amount_and_symbol": true,
    "symbol": "\u0434\u0435\u043d",
    "symbol_on_left": false,
    "thousands_separator": "."
  },
  "MNT": {
    "code": "MNT",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "MNT",
    "name": "Mongolia Tughrik",
    "name_plural": "Mongolia tugriks",
    "number": 496,
    "space_between_amount_and_symbol": false,
    "symbol": "\u20ae",
    "symbol_on_left": true,
    "thousands_separator": "."
  },
  "MUR": {
    "code": "MUR",
    "decimal_digits": 0,
    "decimal_separator": ".",
    "flag": "MUR",
    "name": "Mauritius Rupee",
    "name_plural": "Mauritian rupees",
    "number": 480,
    "space_between_amount_and_symbol": false,
    "symbol": "\u20a8",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "MWK": {
    "code": "MWK",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "MWK",
    "name": "Malawian Kwacha",
    "name_plural": "Malawian kwachas",
    "number": 454,
    "space_between_amount_and_symbol": false,
    "symbol": "MK",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "MZN": {
    "code": "MZN",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "MZN",
    "name": "Mozambique Metical",
    "name_plural": "Mozambican meticals",
    "number": 943,
    "space_between_amount_and_symbol": false,
    "symbol": "MT",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "NAD": {
    "code": "NAD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "NAD",
    "name": "Namibia Dollar",
    "name_plural": "Namibian dollars",
    "number": 516,
    "space_between_amount_and_symbol": false,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "NGN": {
    "code": "NGN",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "NGN",
    "name": "Nigeria Naira",
    "name_plural": "Nigerian nairas",
    "number": 566,
    "space_between_amount_and_symbol": false,
    "symbol": "\u20a6",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "NIO": {
    "code": "NIO",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "NIO",
    "name": "Nicaragua Cordoba",
    "name_plural": "Nicaraguan c\u00f3rdobas",
    "number": 558,
    "space_between_amount_and_symbol": true,
    "symbol": "C\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "NPR": {
    "code": "NPR",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "NPR",
    "name": "Nepal Rupee",
    "name_plural": "Nepalese rupees",
    "number": 524,
    "space_between_amount_and_symbol": false,
    "symbol": "\u20a8",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "OMR": {
    "code": "OMR",
    "decimal_digits": 3,
    "decimal_separator": ".",
    "flag": "OMR",
    "name": "Oman Rial",
    "name_plural": "Omani rials",
    "number": 512,
    "space_between_amount_and_symbol": true,
    "symbol": "\ufdfc",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "PEN": {
    "code": "PEN",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "PEN",
    "name": "Peru Sol",
    "name_plural": "Peruvian nuevos soles",
    "number": 604,
    "space_between_amount_and_symbol": true,
    "symbol": "S/.",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "PGK": {
    "code": "PGK",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "PGK",
    "name": "Papua New Guinean Kina",
    "name_plural": "Papua New Guinean Kina",
    "number": 598,
    "space_between_amount_and_symbol": false,
    "symbol": "K",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "PKR": {
    "code": "PKR",
    "decimal_digits": 0,
    "decimal_separator": ".",
    "flag": "PKR",
    "name": "Pakistan Rupee",
    "name_plural": "Pakistani rupees",
    "number": 586,
    "space_between_amount_and_symbol": false,
    "symbol": "\u20a8",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "PYG": {
    "code": "PYG",
    "decimal_digits": 0,
    "decimal_separator": ",",
    "flag": "PYG",
    "name": "Paraguay Guarani",
    "name_plural": "Paraguayan guaranis",
    "number": 600,
    "space_between_amount_and_symbol": true,
    "symbol": "\u20b2",
    "symbol_on_left": true,
    "thousands_separator": "."
  },
  "QAR": {
    "code": "QAR",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "QAR",
    "name": "Qatar Riyal",
    "name_plural": "Qatari rials",
    "number": 634,
    "space_between_amount_and_symbol": true,
    "symbol": "\ufdfc",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "RSD": {
    "code": "RSD",
    "decimal_digits": 0,
    "decimal_separator": ",",
    "flag": "RSD",
    "name": "Serbia Dinar",
    "name_plural": "Serbian dinars",
    "number": 941,
    "space_between_amount_and_symbol": true,
    "symbol": "\u0414\u0438\u043d.",
    "symbol_on_left": false,
    "thousands_separator": "."
  },
  "SOS": {
    "code": "SOS",
    "decimal_digits": 0,
    "decimal_separator": ".",
    "flag": "SOS",
    "name": "Somalia Shilling",
    "name_plural": "Somali shillings",
    "number": 706,
    "space_between_amount_and_symbol": false,
    "symbol": "S",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "SRD": {
    "code": "SRD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "SRD",
    "name": "Suriname Dollar",
    "name_plural": "Suriname Dollar",
    "number": 968,
    "space_between_amount_and_symbol": false,
    "symbol": "\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "TTD": {
    "code": "TTD",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "TTD",
    "name": "Trinidad and Tobago Dollar",
    "name_plural": "Trinidad and Tobago dollars",
    "number": 780,
    "space_between_amount_and_symbol": false,
    "symbol": "TT\$",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "TZS": {
    "code": "TZS",
    "decimal_digits": 0,
    "decimal_separator": ".",
    "flag": "TZS",
    "name": "Tanzanian Shilling",
    "name_plural": "Tanzanian shillings",
    "number": 834,
    "space_between_amount_and_symbol": false,
    "symbol": "TSh",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "UAH": {
    "code": "UAH",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "UAH",
    "name": "Ukraine Hryvnia",
    "name_plural": "Ukrainian hryvnias",
    "number": 980,
    "space_between_amount_and_symbol": false,
    "symbol": "\u20b4",
    "symbol_on_left": false,
    "thousands_separator": "."
  },
  "UGX": {
    "code": "UGX",
    "decimal_digits": 0,
    "decimal_separator": ".",
    "flag": "UGX",
    "name": "Ugandan Shilling",
    "name_plural": "Ugandan shillings",
    "number": 800,
    "space_between_amount_and_symbol": false,
    "symbol": "USh",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "UYU": {
    "code": "UYU",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "UYU",
    "name": "Uruguay Peso",
    "name_plural": "Uruguayan pesos",
    "number": 858,
    "space_between_amount_and_symbol": true,
    "symbol": "\$U",
    "symbol_on_left": true,
    "thousands_separator": "."
  },
  "VEF": {
    "code": "VEF",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "VEF",
    "name": "Venezuela Bol\u00edvar",
    "name_plural": "Venezuelan bol\u00edvars",
    "number": 937,
    "space_between_amount_and_symbol": true,
    "symbol": "Bs",
    "symbol_on_left": true,
    "thousands_separator": "."
  },
  "VND": {
    "code": "VND",
    "decimal_digits": 0,
    "decimal_separator": ".",
    "flag": "VND",
    "name": "Viet Nam Dong",
    "name_plural": "Vietnamese dong",
    "number": 704,
    "space_between_amount_and_symbol": true,
    "symbol": "\u20ab",
    "symbol_on_left": false,
    "thousands_separator": "."
  },
  "YER": {
    "code": "YER",
    "decimal_digits": 0,
    "decimal_separator": ".",
    "flag": "YER",
    "name": "Yemen Rial",
    "name_plural": "Yemeni rials",
    "number": 886,
    "space_between_amount_and_symbol": true,
    "symbol": "\ufdfc",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "ALL": {
    "code": "ALL",
    "decimal_digits": 0,
    "decimal_separator": ",",
    "flag": "ALB",
    "name": "Albanian Lek",
    "name_plural": "Albanian lek\u00eb",
    "number": 8,
    "space_between_amount_and_symbol": false,
    "symbol": "Lek",
    "symbol_on_left": false,
    "thousands_separator": "."
  },
  "AMD": {
    "code": "AMD",
    "decimal_digits": 0,
    "decimal_separator": ".",
    "flag": "AM",
    "name": "Armenian Dram",
    "name_plural": "Armenian drams",
    "number": 51,
    "space_between_amount_and_symbol": true,
    "symbol": "\u058f",
    "symbol_on_left": false,
    "thousands_separator": ","
  },
  "AZN": {
    "code": "AZN",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "AZE",
    "name": "Azerbaijani Manat",
    "name_plural": "Azerbaijani manats",
    "number": 100,
    "space_between_amount_and_symbol": true,
    "symbol": "\u20bc",
    "symbol_on_left": false,
    "thousands_separator": "."
  },
  "BI": {
    "code": "BI",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "BI",
    "name": "Burundian Franc",
    "name_plural": "Burundian Franc",
    "number": 108,
    "space_between_amount_and_symbol": true,
    "symbol": "FBu",
    "symbol_on_left": true,
    "thousands_separator": "."
  },
  "BWP": {
    "code": "BWP",
    "decimal_digits": 2,
    "decimal_separator": ".",
    "flag": "BW",
    "name": "Botswanan Pula",
    "name_plural": "Botswanan pulas",
    "number": 72,
    "space_between_amount_and_symbol": false,
    "symbol": "P",
    "symbol_on_left": true,
    "thousands_separator": ","
  },
  "BYN": {
    "code": "BYN",
    "decimal_digits": 2,
    "decimal_separator": ",",
    "flag": "BY",
    "name": "Belarussian Ruble",
    "name_plural": "Belarusian rubles",
    "number": 933,
    "space_between_amount_and_symbol": true,
    "symbol": "Br",
    "symbol_on_left": true,
    "thousands_separator": "."
  }
};
